[package]
name = "printer_info"
version = "0.1.0"
edition = "2021"
authors = ["LuznyKamus1"]
repository = "https://github.com/LuznyKamus1/printer_info.git"

[dependencies]
curl = "0.4.44"
json = "0.12.4"
serde_json = "1.0.113"
